# Generated by Django 3.0.6 on 2020-05-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('description', models.TextField(blank=True, default='')),
                ('summary', models.TextField(default='', help_text='内容説明を入力してください')),
            ],
        ),
    ]
