# Generated by Django 3.0.6 on 2020-05-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200518_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.IntegerField(default=64),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.IntegerField(default=64),
        ),
    ]
